var correctAnswer;
var displayAnswer;
var score = 0;
var gameStarted = false;
var timeOut = setTimeout(function(){}, 5000);
var gameMode = 0;
var musicOn = true;
var arcadeBest = 0;
var timedBest = 0;
var arcadeTimes = 0;
var timedTimes = 0;
var arcadeAvg = 0;
var timedAvg = 0;
var colour_assist = false;
var arcadeBestNoAssist = 0;
var timedBestNoAssist = 0;
var arcadeTimesNoAssist = 0;
var timedTimesNoAssist = 0;
var arcadeAvgNoAssist = 0;
var timedAvgNoAssist = 0;